artifacts:
  - name: "@daiyam/artifact-base"
    version: 0.5.0
  - name: "@daiyam/artifact-lang-ts"
    version: 0.5.6
  - name: "@daiyam/artifact-vsx-ts"
    version: 0.7.2
  - name: "@daiyam/artifact-vsx-zokugun"
    version: 0.3.1
